### PR TITLE
Update the current team

### PR DESCRIPTION
**Pull request by DaniElectra**
Simple change

### CODE REVIEW

**Comment by jonbarrow** [comment]
I've been wanting to do this anyway, but I want to move random from the team section to the special thanks section

Would you mind covering this in this PR too? Then I'll merge it

**Comment by DaniElectra** [comment]
I didn't want to touch other things as it would mess with other translations right? so i would have to move them on the translations too

**Comment by DaniElectra** [comment]
Alright, the only thing missing is probably updating descriptions

**Comment by DaniElectra** [comment]
The credits descriptions are now updated and the translations of the people have been removed, as told in Discord

**Comment by jonbarrow** [comment]
lgtm

**Pull request merged**
