### PR TITLE
Fully translate and correct ES_es.json

### PR DESCRIPTION
**Pull request by eros71-dev**
Translated the missing strings and updated some to sound more natural.

### CODE REVIEW

**Comment by ashmonty** [comment]
Thank you for your contribution!

**Comment by ashmonty** [comment]
Hey @eros71-dev, I'm Ash from the Pretendo Network developer team.

I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.

Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)

P.S: I'm asking you here because I wasn't sure where to reach you otherwise

**Comment by eros71-dev** [comment]
Of course I do! Feel free to change the license. You can also contact me on discord: eros71#9555 , if you have any more questions.

**Comment by ashmonty** [comment]
Great! Thank you very much!

**Comment by eros71-dev** [comment]
No problem!

**Pull request merged**
