### PR TITLE
Moved from Trello to GitHub porjects

### PR DESCRIPTION
**Pull request by jonbarrow**
this PR moves the websites progress tracking away from Trello and on to GitHub pages

### CODE REVIEW

**Review by ashmonty — APPROVED** [review]
lgtm

**Comment by ashmonty** [comment]
porjects

**Comment by jonbarrow** [comment]
> porjects

I made this commitat 4am cut me some slack

**Comment by ashmonty** [comment]
> I made this commitat 4am cut me some slack
Not this reply tho

commitat

**Pull request merged**
