### PR TITLE
Norwegian (Bokmål) localization

### PR DESCRIPTION
**Pull request by Odyssey346**
There were some words I didn't really find a proper translation for (Like reverse engineering) so I just took it a bit literal/found another replacement.

### CODE REVIEW

**Comment by sjkim04** [comment]
Maybe you could readd the PR to the dev branch, as the repository only accepts PRs to ‘dev’ branch, and then merge to master

**Comment by Odyssey346** [comment]
I did point it to master. I'm stupid -_- I'll fix it tomorrow

**Comment by ashmonty** [comment]
Hey, thanks for your contribution!
Don't worry about the wrong branch, just gonna merge into master since the git tree needs cleaning up anyways

**Comment by ashmonty** [comment]
Hey @Odyssey346, I'm Ash from the Pretendo Network developer team.

I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.

Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)

P.S: I'm asking you here because I wasn't sure where to reach you otherwise

**Comment by Odyssey346** [comment]
that's fine by meSendt fra min Galaxy

**Comment by ashmonty** [comment]
Nice, thank you very much!

**Pull request merged**
