### PR TITLE
feature: docs

### PR DESCRIPTION
**Pull request by ashmonty**
- [add search, minor style changes](https://github.com/PretendoNetwork/website/commit/76edfe0a02c0667778f16b72c12faf86b368b41a)
- [install platform selection w/ icons, subpage router support](https://github.com/PretendoNetwork/website/commit/3f56ae3f9b72006f6f184204337f4947faba679d)
- [mobile layout, tips, minor changes](https://github.com/PretendoNetwork/website/commit/976a7861aaba516b7e4f886d4b2300fcd8f2ebbd)
- misc fixes, minor changes

### CODE REVIEW

**Comment by jonbarrow** [comment]
This branch seems to be based on an out dated branch, the cache system still relies on Trello. Please update to be compatible with the latest dev

**Review by jonbarrow — CHANGES_REQUESTED** [review]
This branch seems to be based on an out dated branch, the cache system still relies on Trello. Please update to be compatible with the latest dev

**Comment by ashmonty** [comment]
> This branch seems to be based on an out dated branch, the cache system still relies on Trello. Please update to be compatible with the latest dev

It is compatible with the latest dev, is it not? I didn't touch any of the cache stuff, so as long as you just merge the pr there's no need to update anything

**Comment by ashmonty** [comment]
Oh wait I see what you mean

**Comment by ashmonty** [comment]
Ok no I actually don't see what you mean. I haven't touched the cache system, so a simple merge of the pr would do the job

**Comment by jonbarrow** [comment]
It seems like your other commit fixed another issue I was having where I couldn't login even after removing the old Trello cache system manually

**Comment by ashmonty** [comment]
Yeah I accidentally pushed the workaround I needed to use to be able to work on the website without asking you to whitelist my ip lol. Whoops

**Comment by jonbarrow** [comment]
Looks good to me so far. Maybe we should actually write the docs though before merging? I don't exactly want a half-finished feature merged

**Comment by ashmonty** [comment]
Sounds good to me!

**Review by jonbarrow — APPROVED** [review]

**Pull request merged**
