### PR TITLE
Update BR_pt.json

### PR DESCRIPTION
**Pull request by ninstar**
- Translated new and missing fields.
- Removed a few text redundancies.
- Changed "3DS" and "Switch" to "Nintendo 3DS" and "Nintendo Switch" respectively.
- Changed all mentions to "Pretendo" and "Pretendo Network" from masculine noun (o, do, no) to female noun (a, da, na).

### CODE REVIEW

**Comment by jonbarrow** [comment]
Question about the last change, why did you change from masculine to feminine? Just curious is all

**Comment by ninstar** [comment]
> Question about the last change, why did you change from masculine to feminine? Just curious is all

Because "Network" uses feminine noun in Portuguese. So calling it "**A** Pretendo Network" makes more sense.

**Comment by jonbarrow** [comment]
> > Question about the last change, why did you change from masculine to feminine? Just curious is all
> 
> 
> 
> Because "Network" uses feminine noun in Portuguese. So calling it "**A** Pretendo Network" makes more sense.

Got it! Thanks for the info

**Comment by montylion** [comment]
Looks good to me! Thanks for your contribution

**Pull request merged**
