### PR TITLE
Feat: bandwidth

### PR DESCRIPTION
**Pull request by ashmonty**
get it it's feat as in feature and also featuring hahahahahaha

### CODE REVIEW

**Comment by GuestDreemurr** [comment]
sunny omori approved :+1:

**Review by mrjvs — APPROVED** [review]

**Comment by oscie57** [comment]
if this isnt added i will skin the denier :D

**Comment by GuestDreemurr** [comment]
> if this isnt added i will skin the denier :D

and i will send them into fire

**Comment by GuestDreemurr** [comment]
disposing of the evidence

**Comment by ashmonty** [comment]
looks ready to me. @jonbarrow mind taking a look

**Comment by ashmonty** [comment]
This is gonna be fun to localize lmao

**Pull request merged**
