### PR TITLE
fix FBI link

### PR DESCRIPTION
**Pull request by marnie-mary**

### CODE REVIEW

**Review by DaniElectra — APPROVED** [review]
Assuming there aren't any other references, looks good to me

Fixes #253

**Comment by DaniElectra** [comment]
Well actually, you need to change the target branch to the `dev` branch, and not the `master` branch

**Review by gitlimes — APPROVED** [review]
LGTM!

**Comment by marnie-marnie-marnie-marnie-marnie** [comment]
thanks for changing the branch, im new at this haha

**Comment by DaniElectra** [comment]
@jonbarrow This should be good to merge

**Pull request merged**
