### PR TITLE
Update it_IT.json

### PR DESCRIPTION
**Pull request by KintsugiUwU**
Removed unnecessary words and improved general phrases

### CODE REVIEW

**Comment by Silver-Volt4** [comment]
fyi, you don't have to close a pull request to make changes to it, just push new changes to the branch that's being PR'd (in your case that's KintsugiUwU:master)

**Comment by KintsugiUwU** [comment]
My bad, did a quick fix in a hurry and got messed up, opened a new pull request instead of a simple push

**Comment by jonbarrow** [comment]
You're working on the wrong branch. Target dev not master

**Comment by ashquarky** [comment]
Hi, sorry this has been left for a while - unfortunately in the meantime the strings have changed so much that it's not really viable for us to merge translations over Git since weblate will still mark them as broken.

Weblate is working again, please submit translations there: https://hosted.weblate.org/projects/pretendonetwork/website/

**Pull request closed without merging**
