### PR TITLE
Improve german translation

### PR DESCRIPTION
**Pull request by CyberYoshi64**
Fixed typos, untranslated left-overs mid-sentence and bad use of grammar
Left the `localizationPage` portion as-is, unsure whether to actually translate it

### CODE REVIEW

**Comment by ashmonty** [comment]
Looks good to me. Thanks for your contribution!

**Comment by ashmonty** [comment]
Hey @CyberYoshi64, I'm Ash from the Pretendo Network developer team.

I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.

Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)

P.S: I'm asking you here because I wasn't sure where to reach you otherwise

**Comment by CyberYoshi64** [comment]
Hello Ash,
I agree to relicense my contributions.
However, I am not aware on how you would change a license? Is it just changing the LICENSE.md?

About the P.S.: It's fine. I happen to have the GitHub app to stay in touch, although my e-Mail address suffices too.
(If you wonder why I left the Discord server, it was as my account got hacked and I understand how you scrambled informing me at that point.)

**Comment by ashmonty** [comment]
Thank you very much! Once we apply the license to the repository, all previous contributions will fall under the new license, you don't have to do anything else; all we needed was a confirmation

**Pull request merged**
