### PR TITLE
Update FAQ entries for public release and SSSL

### PR DESCRIPTION
**Pull request by ashquarky**
Some of the FAQ entries are pretty far out of date and give people the wrong information. Update these to mention that we have public, free servers, and talk about Aroma and SSSL instead of Coldboot Haxchi.

### CODE REVIEW

**Comment by ashquarky** [comment]
I have no idea what needs to happen for Weblate to be aware of these changes, btw

**Comment by jonbarrow** [comment]
LGTM. @hauntii @gitlimes can you confirm that Weblate won't implode with these changes?

**Review by jonbarrow — APPROVED** [review]

**Comment by gitlimes** [comment]
It shouldn't, no!

**Comment by jonbarrow** [comment]
@gitlimes I forgot to ask this the other day, but how does this affect other languages? Will this invalidate the other translations? Will they remain outdated? How does that work with Weblate

**Comment by gitlimes** [comment]
They will be shown as outdated on the website interface. There is also an option in the we late interface to delete outdated translation strings from the locale files, which should probably be used.

**Pull request merged**
