### PR TITLE
BR_pt - fix misspelled words and special thanks translation

### PR DESCRIPTION
**Pull request by FerroEduardo**
* Fix a misspelled word
* Based on other locales, the Special Thanks title and text were translated
    * At least for me, it does not make sense of being the only which was not translated

### CODE REVIEW

**Comment by ashmonty** [comment]
Looks good to me, thanks for your contribution!

**Comment by ashmonty** [comment]
Hey @FerroEduardo, I'm Ash from the Pretendo Network developer team.

I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.

Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)

P.S: I'm asking you here because I wasn't sure where to reach you otherwise

**Comment by FerroEduardo** [comment]
Hi @ashmonty, I agree. Do I need to do anything or this message is enough?

**Comment by ashmonty** [comment]
Nope, the message is enough. Thank you very much!

**Pull request merged**
